#ifndef _VIDEO_GR_MACROS
#define _VIDEO_GR_MACROS

#define MOVEMENT_STEP 5;
#define SIZE_FRONT_END 5;
#define COLOR_PLAYER1 0x1F51FF;
#define COLOR_PLAYER2 0xFF5F1F;
#define MOUSE_BORDER_WIDTH 30
#define VBE_SERVICES 0x4F;
#define SET_VBE_MOD 0x02
#define ENABLE_LIN_BUF BIT(14)
#define BIOS_VIDEO_SERVICES 0x10
#define NIGHT_BACKGROUND 0x000000
#define DAY_BACKGROUND 0xFFFFFF
#define TRANSPARENCY 0x123456

#endif
